services:
  asspp:
    image: yuccc/assppweb:server-accounts
    ports:
      - "8080:8080"
    volumes:
      - ./mnt/asspp-data:/data
    environment:
      - DATA_DIR=/data
      - PORT=8080
      - DOWNLOAD_THREADS=8
      - ACCESS_PASSWORD=123456
      - AUTO_CLEANUP_DAYS=3
      - AUTO_CLEANUP_MAX_MB=1024
      - MAX_DOWNLOAD_MB=0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "5"
